# Generated by Django 5.0.6 on 2024-06-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('job_nature', models.CharField(choices=[('Full time', 'Fulltime'), ('part time', 'Parttime'), ('Remotly', 'Remotly')], default='Full time', max_length=50)),
                ('strat_salary', models.IntegerField()),
                ('end_salary', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('lookingfor', models.CharField(max_length=300)),
                ('requirements', models.CharField(max_length=300)),
                ('jop_feature', models.CharField(max_length=300)),
                ('education', models.CharField(max_length=300)),
            ],
        ),
    ]
